---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: https://api.netlify.com/build_hooks/61cd40d06b8065248ad74baa
sections:
- type: document
  path: config.toml
  label: Config.toml
- type: directory
  path: about
  label: About
  create: all
  match: "*"
- type: directory
  path: data
  label: Data
  create: all
  match: "*"
  new_doc_ext: yml
upload_dir: static/images
public_path: images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
